### ISSUE TITLE
Bug Report: Scaling of the diggable blocks

### ISSUE THREAD

**Issue by rbakerusw** [PlaceholderGames/2016-VnD_Game#66] opened 2017-03-16 14:13 UTC
Currently there is an issue with the scaling of the blocks you can dig/mine. The scaling is set by default to 2 so you cannot have custom shaped blocks to dig/mine.

I will work on this straight away since we have to use the block in a specific way due to the restrictions of the scaling.

**Comment by rbakerusw** [comment] 2017-03-16 15:27
This issue has now been fixed, you can now create custom shaped digging blocks. Also, I had to fix the mining trigger box due to a compiler error.

**Comment by napiorek** [comment] 2017-03-18 10:43
Tested and it works great, the cube shrinks from it's original size as intended.
Also feature was only triggered when pressed 3 (digging) and ignored button 2 that is linked to mining(with pickaxe) so it works as designed :)
![image](https://cloud.githubusercontent.com/assets/22525895/24071340/38cc4b3a-0bc7-11e7-8986-ec1b2c62ea90.png)

Good work @rbakerusw

**Comment by BojanStankovic** [comment] 2017-03-18 17:14
Merged into develop. Closing

**Closed as completed by BojanStankovic** 2017-03-18 17:14 UTC
